---
# Ansible Galaxy requirements for Windows VM Health Check
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.windows
    version: ">=1.14.0"
  - name: community.windows
    version: ">=1.13.0"
  - name: ansible.posix
    version: ">=1.5.0"

roles: []
  # Add any required roles here if needed in the future
  # - name: ansible.windows.win_updates
  #   version: "1.0.0"